const vendingMachines = [
  {"state": "CA", "city": "Alameda", "location": "Safeway (Q01036, 2227 S Shore Center)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Alameda", "location": "Safeway (Q01268, 2600 5th St)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "American Canyon", "location": "Safeway (Q01528, 103 American Canyon Rd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Anaheim", "location": "Food 4 Less (Q00330, 1616 W Katella Ave)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Anaheim", "location": "Albertsons (Q00491, 810 S State College Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Anaheim", "location": "Vons (Q00695, 5600 E Santa Ana Canyon Rd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Aptos", "location": "Safeway (Q01333, 16 Rancho del Mar)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Arcadia", "location": "Albertsons (Q00467, 298 Live Oak Ave)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Arcadia", "location": "Vons (Q00715, 745 W Naomi Ave)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Arleta", "location": "Food 4 Less (Q00319, 9635 Laurel Canyon Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Auburn", "location": "Safeway (Q00918, 2550 Bell Rd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Baldwin Park", "location": "Food 4 Less (Q00573, 3000 Baldwin Park Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Banning", "location": "Albertsons (Q01691, 300 S Highland Springs Ave)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Bell Gardens", "location": "Food 4 Less (Q00711, 6901 Eastern Ave)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Belmont", "location": "Safeway (Q01083, 1100 El Camino Real)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Benicia", "location": "Safeway (Q01274, 50 Solano Square)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Berkeley", "location": "Safeway (Q01020, 1444 Shattuck Pl)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Brentwood", "location": "WinCo Foods (Q00597, 6700 Lone Tree Wy)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Burbank", "location": "Vons (Q00314, 301 N Pass Ave)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Calabasas", "location": "Albertsons (Q00523, 26521 Agoura Rd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Camarillo", "location": "Vons (Q01242, 940 Arneill RD)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Cameron Park", "location": "Safeway (Q00974, 3380 Coach Ln)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Campbell", "location": "Safeway (Q00971, 2341 S Winchester Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Campbell", "location": "Safeway (Q01539, 950 W Hamilton Ave)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Carlsbad", "location": "Vons (Q00875, 2560 El Camino Real)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Carlsbad", "location": "Vons (Q01024, 6951 El Camino Real)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Carmichael", "location": "Safeway (Q00989, 4040 Manzanita Ave)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Carson", "location": "Albertsons (Q00722, 200 E Sepulveda Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Castro Valley", "location": "Safeway (Q01102, 4015 E Castro Valley Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Chino", "location": "Albertsons (Q00509, 12013 Central Ave)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Chino Hills", "location": "Albertsons (Q00519, 15970 Los Serranos Country Club Dr)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Chino Hills", "location": "Albertsons (Q01243, 3255 Grand Ave)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Chula Vista", "location": "Vons (Q00331, 1745 Eastlake Pkwy)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Chula Vista", "location": "Vons (Q01032, 2250 Otay Lakes Rd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Chula Vista", "location": "Albertsons (Q01670, 720 3rd Ave)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Chula Vista", "location": "Ralphs (Q01791, 659 E Palomar St)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Citrus Heights", "location": "Safeway (Q00941, 7301 Greenback Ln)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Colton", "location": "Food 4 Less (Q01692, 1150 N Pepper Ave)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Compton", "location": "Food 4 Less (Q00409, 1900 W Rosecrans Ave)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Concord", "location": "Safeway (Q00970, 2600 Willow Pass Rd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Concord", "location": "Safeway (Q01279, 4309 Clayton Rd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Corona", "location": "Albertsons (Q00388, 260 W Foothill Pkwy)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Corona", "location": "Vons (Q00508, 535 N McKinley St)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Corona", "location": "Vons (Q00511, 11800 De Palma Rd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Corte Madera", "location": "Safeway (Q01512, 137 Corte Madera Town Center)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Costa Mesa", "location": "Ralphs (Q01781, 380 E 17th St)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Culver City", "location": "Pavilions (Q00517, 11030 Jefferson Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Cupertino", "location": "Safeway (Q01486, 20620 W Homestead Rd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Daly City", "location": "Safeway (Q01516, 601 Westlake Center)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Danville", "location": "Safeway (Q01151, 3496 Camino Tassajara)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Dixon", "location": "Safeway (Q01320, 1235 Stratford Ave)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Downey", "location": "Food 4 Less (Q00311, 13525 Lakewood Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Downey", "location": "Ralphs (Q00739, 8626 Firestone Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Dublin", "location": "Safeway (Q00928, 7499 Dublin Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Dublin", "location": "Safeway (Q00930, 4440 Tassajara Rd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Eastvale", "location": "Albertsons (Q00655, 7070 Archibald Ave)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Eastvale", "location": "Vons (Q01167, 6170 Hamner Ave)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "El Cajon", "location": "Albertsons (Q00474, 1608 Broadway)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "El Cajon", "location": "Vons (Q00886, 1201 Avocado Ave)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "El Cajon", "location": "Albertsons (Q01247, 2899 Jamacha Rd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "El Cerrito", "location": "Safeway (Q01018, 11450 San Pablo Ave)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "El Cerrito", "location": "Lucky (Q01758, 1000 El Cerrito Plaza)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "El Dorado Hills", "location": "Safeway (Q00938, 2207 Francisco Dr)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "El Dorado Hills", "location": "Safeway (Q00977, 3383 Bass Lake Rd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Elk Grove", "location": "Safeway (Q00931, 5021 Laguna Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Elk Grove", "location": "WinCo Foods (Q01530, 8124 Sheldon Rd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Emeryville", "location": "Pak N Save (Q01060, 3889 San Pablo Ave)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Escondido", "location": "Albertsons (Q00890, 1570 W Valley Pkwy)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Escondido", "location": "Vons (Q00892, 1000 W El Norte Pkwy)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Escondido", "location": "Vons (Q01030, 351 W Felicita Ave)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Escondido", "location": "Food 4 Less (Q01250, 644 N Broadway)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Fair Oaks", "location": "Safeway (Q00943, 5450 Dewey Dr)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Fairfield", "location": "Safeway (Q01334, 2401 Waterman Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Fallbrook", "location": "Albertsons (Q00476, 1133 S Mission Rd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Fillmore", "location": "Vons (Q00481, 636 Ventura St)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Folsom", "location": "WinCo Foods (Q00690, 200 Blue Ravine Rd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Folsom", "location": "Safeway (Q00981, 1850 Prairie City Rd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Fontana", "location": "WinCo Foods (Q00493, 14338 Foothill Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Fontana", "location": "Vons (Q00563, 7390 Cherry Ave)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Foster City", "location": "Safeway (Q01239, 921 E Hillsdale Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Fountain Valley", "location": "Albertsons (Q00328, 16061 Brookhurst St)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Freedom", "location": "Safeway (Q01337, 2010 Freedom Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Fremont", "location": "Safeway (Q00973, 39100 Argonaut Way)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Fremont", "location": "Safeway (Q01026, 3902 Washington Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Fullerton", "location": "Albertsons (Q00332, 1930 N Placentia Ave)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Garden Grove", "location": "Vons (Q00717, 11861 Valley View St)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Gardena", "location": "Vons (Q00658, 1260 W Redondo Beach Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Gardena", "location": "Albertsons (Q00732, 1735 Artesia Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Gardena", "location": "Food 4 Less (Q01249, 1299 Artesia Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Glendale", "location": "Vons (Q00417, 561 N Glendale Ave)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Glendale", "location": "Vons (Q00699, 311 W Los Feliz Rd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Glendora", "location": "Albertsons (Q00427, 133 W Rte 66)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Goleta", "location": "Vons (Q01245, 163 S Turnpike Rd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Granada Hills", "location": "Vons (Q00702, 16830 San Fernando Mission Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Hacienda Heights", "location": "Vons (Q00707, 2122 S Hacienda Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Half Moon Bay", "location": "Safeway (Q01277, 70 Cabrillo Hwy)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Hawthorne", "location": "Food 4 Less (Q00315, 14500 Ocean Gate Ave)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Hayward", "location": "FoodMaxx (Q00626, 27300 Hesperian Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Hayward", "location": "Safeway (Q01051, 22280 Foothill Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Hayward", "location": "Safeway (Q01278, 231 W Jackson St)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Healdsburg", "location": "Safeway (Q01502, 1115 Vine St)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Hemet", "location": "WinCo Foods (Q00453, 4602 W Florida Ave)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Hercules", "location": "Safeway (Q00939, 4080 San Pablo Ave)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Hermosa Beach", "location": "Vons (Q00721, 715 Pier Ave)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Huntington Beach", "location": "Vons (Q00322, 5922 Edinger Ave)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Huntington Beach", "location": "Albertsons (Q00325, 7201 Yorktown Ave)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Huntington Beach", "location": "Albertsons (Q00483, 19640 Beach Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Huntington Park", "location": "Food 4 Less (Q00418, 6920 Santa Fe Ave)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Inglewood", "location": "Food 4 Less (Q00380, 3200 W Century Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Inglewood", "location": "Vons (Q00422, 500 E Manchester Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Irvine", "location": "Albertsons (Q00416, 14201 Jeffrey Rd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Irvine", "location": "Albertsons (Q00590, 4541 Campus Dr)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Irvine", "location": "Albertsons (Q01285, 6601 Quail Hill Pkwy)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Jackson", "location": "Safeway (Q00922, 12110 Industry Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "La Crescenta-Montrose", "location": "Vons (Q01241, 3233 Foothill Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "La Habra", "location": "Albertsons (Q00583, 1800 W Whittier Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "La Jolla", "location": "Pavilions (Q00576, 7544 Girard Ave)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "La Mesa", "location": "Albertsons (Q00878, 8920 Fletcher Pkwy)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "La Mirada", "location": "Albertsons (Q01777, 15200 Rosecrans Ave)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "La Puente", "location": "Food 4 Less (Q00338, 1821 N Hacienda Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "La Verne", "location": "Vons (Q00515, 1600 Foothill Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Ladera Ranch", "location": "Albertsons (Q00498, 27702 Crown Valley Pkwy B)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Laguna Niguel", "location": "Albertsons (Q01007, 30241 Golden Lantern)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Lake Elsinore", "location": "Albertsons (Q00518, 30901 Riverside Dr)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Lakewood", "location": "Vons (Q00317, 4226 Woodruff Ave)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Lakewood", "location": "Vons (Q00740, 5500 Woodruff Ave)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Lakewood", "location": "WinCo Foods (Q01286, 3400 E South St)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Livermore", "location": "Safeway (Q00987, 1554 First St)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Livermore", "location": "Safeway (Q01049, 4495 First St)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Long Beach", "location": "Vons (Q00654, 1800-2000 Ximeno Ave)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Long Beach", "location": "Food 4 Less (Q00720, 3210 E Anaheim St)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Long Beach", "location": "Albertsons (Q01019, 101 E Willow St)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Los Altos", "location": "Safeway (Q01517, 160 1st St)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Los Angeles", "location": "Food 4 Less (Q00324, 5100 N Figueroa St)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Los Angeles", "location": "Vons (Q00336, 3461 W 3rd St)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Los Angeles", "location": "Food 4 Less (Q00386, 11507 S Western Ave)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Los Angeles", "location": "Food 4 Less (Q00391, 11840 Wilmington Ave)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Los Angeles", "location": "Food 4 Less (Q00411, 18318 Vanowen St)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Los Angeles", "location": "Food 4 Less (Q00413, 1820 W Slauson Ave)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Los Angeles", "location": "Food 4 Less (Q00420, 2750 1st St)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Los Angeles", "location": "Vons (Q00425, 4520 W Sunset Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Los Angeles", "location": "Pavilions (Q00514, 6534 Platt Ave)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Los Angeles", "location": "Vons (Q00577, 7789 Foothill Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Los Angeles", "location": "Vons (Q00719, 7311 N Figueroa St)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Los Angeles", "location": "Food 4 Less (Q01694, 12689 Glenoaks Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Los Gatos", "location": "Safeway (Q00978, 470 N Santa Cruz Ave)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Los Gatos", "location": "Safeway (Q00983, 15549 Union Ave)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Manteca", "location": "Safeway (Q00980, 1187 S Main St)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Marina del Rey", "location": "Pavilions (Q00512, 4365 Glencoe Ave)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Martinez", "location": "Safeway (Q01109, 6688 Alhambra Ave)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Menlo Park", "location": "Safeway (Q01330, 525 El Camino Real)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Millbrae", "location": "Safeway (Q01510, 525 El Camino Real)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Milpitas", "location": "Safeway (Q00982, 555 E Calaveras Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Mission Hills", "location": "Vons (Q00501, 10321 Sepulveda Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Mission Viejo", "location": "Albertsons (Q00575, 23072 Alicia Pkwy)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Mission Viejo", "location": "Pavilions (Q01270, 26022 Marguerite Pkwy)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Monrovia", "location": "Vons (Q00335, 130 W Foothill Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Montebello", "location": "Albertsons (Q00704, 2469 Via Campo)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Moorpark", "location": "Vons (Q01792, 4241 Tierra Rejada Rd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Moraga", "location": "Safeway (Q01233, 1355 Moraga Way)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Moreno Valley", "location": "WinCo Foods (Q00497, 12880 Day St)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Moreno Valley", "location": "Food 4 Less (Q01796, 24440 Alessandro Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Morgan Hill", "location": "Safeway (Q00932, 235 Tennant Station)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Morgan Hill", "location": "Safeway (Q00985, 840 E Dunne Ave)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Mountain View", "location": "Safeway (Q01271, 645 San Antonio Rd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Mountain View", "location": "Safeway (Q01513, 1750 Miramonte Ave)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Mountain View", "location": "Safeway (Q01538, 570 N Shoreline Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Murrieta", "location": "Albertsons (Q00485, 39140 Winchester Rd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Murrieta", "location": "Albertsons (Q00495, 41000 California Oaks Rd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Newhall", "location": "Vons (Q01184, 24160 Lyons Ave)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Newport Beach", "location": "Pavilions (Q00995, 21181 Newport Coast Dr)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "North Hills", "location": "Food 4 Less (Q00419, 16208 Parthenia St)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "North Hollywood", "location": "Food 4 Less (Q00412, 8035 Webb Ave)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Novato", "location": "Safeway (Q01519, 5720 Nave Dr)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Oakland", "location": "FoodMaxx (Q00984, 3000 E 9th St)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Oakland", "location": "Albertsons (Q01126, 5100 Broadway)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Oakland", "location": "Safeway (Q01164, 4100 Redwood Rd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Oakland", "location": "Safeway (Q01267, 6310 College Ave)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Oceanside", "location": "Albertsons (Q00668, 3450 Marron Rd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Oceanside", "location": "Albertsons (Q00751, 4150 Oceanside Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Oceanside", "location": "Vons (Q01005, 845 College Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Oceanside", "location": "WinCo Foods (Q01300, 2245 S El Camino Real)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Oceanside", "location": "Ralphs (Q01658, 101 Old Grove Rd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Ontario", "location": "Food 4 Less (Q01176, 2246 S Euclid Ave)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Orange", "location": "Vons (Q00591, 2684 N Tustin St)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Orangevale", "location": "WinCo Foods (Q01251, 8701 Greenback Ln)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Oxnard", "location": "Vons (Q00494, 2101 N Rose Ave)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Pacifica", "location": "Safeway (Q01344, 1380 Linda Mar Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Pacifica", "location": "Safeway (Q01387, 709 Hickey Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Pasadena", "location": "Vons (Q00372, 2355 E Colorado Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Perris", "location": "WinCo Foods (Q01730, 3150 Case Rd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Petaluma", "location": "Safeway (Q01492, 701 Sonoma Mountain Pkwy)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Petaluma", "location": "Safeway (Q01525, 389 S McDowell Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Pinole", "location": "Lucky (Q01757, 1530 Fitzgerald Dr)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Placerville", "location": "Safeway (Q00969, 3955 Missouri Flat Rd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Pleasant Hill", "location": "Safeway (Q00967, 600 Patterson Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Pleasant Hill", "location": "Safeway (Q01031, 1978 Contra Costa Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Pleasant Hill", "location": "Safeway (Q01148, 707 Contra Costa Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Pleasanton", "location": "Safeway (Q00944, 1701 Santa Rita Rd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Pomona", "location": "WinCo Foods (Q01236, 90 Rio Rancho Rd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Rancho Cordova", "location": "Safeway (Q00935, 10635 Folsom Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Rancho Cucamonga", "location": "Albertsons (Q00468, 11358 Kenyon Way)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Redlands", "location": "Albertsons (Q00475, 450 E Cypress Ave)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Redondo Beach", "location": "Vons (Q00741, 4001 Inglewood Ave)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Riverside", "location": "Albertsons (Q00500, 2975 Van Buren Boulevard)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Riverside", "location": "Vons (Q01097, 3520 Riverside Plaza Dr)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Riverside", "location": "Food 4 Less (Q01129, 4250 Van Buren Boulevard)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Rocklin", "location": "Safeway (Q00631, 2220 Sunset Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Rohnert Park", "location": "Safeway (Q00603, 6340 Commerce Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Rolling Hills Estates", "location": "Pavilions (Q00714, 7 Peninsula Center)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Roseville", "location": "Safeway (Q00923, 8640 Sierra College Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Roseville", "location": "Safeway (Q00927, 1080 Pleasant Grove Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Roseville", "location": "Safeway (Q00929, 989 Sunrise Ave)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Roseville", "location": "Safeway (Q00988, 9045 Woodcreek Oaks Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Sacramento", "location": "Safeway (Q00924, 1814 19th St)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Sacramento", "location": "Safeway (Q00926, 1025 Alhambra Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Sacramento", "location": "Safeway (Q00933, 3320 Arden Wy)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Sacramento", "location": "Safeway (Q00968, 8377 Elk Grove Florin Rd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Sacramento", "location": "Safeway (Q01522, 5345 Elkhorn Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Sacramento", "location": "WinCo Foods (Q01534, 2300 Watt Ave)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Sacramento", "location": "Safeway (Q01537, 2851 Del Paso Rd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "San Anselmo", "location": "Safeway (Q01500, 838 Sir Francis Drake Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "San Clemente", "location": "Albertsons (Q00521, 804 Avenida Pico)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "San Clemente", "location": "Pavilions (Q01291, 989 Avenida Pico)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "San Diego", "location": "Vons (Q00489, 620 Dennery Rd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "San Diego", "location": "Vons (Q00492, 11986 Bernardo Plaza Dr)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "San Diego", "location": "Vons (Q00499, 6155 El Cajon Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "San Diego", "location": "Vons (Q00505, 8310 Mira Mesa Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "San Diego", "location": "Vons (Q00506, 515 Washington St)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "San Diego", "location": "Albertsons (Q00572, 12475 Rancho Bernardo Rd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "San Diego", "location": "Albertsons (Q00581, 8650 Lake Murray Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "San Diego", "location": "Vons (Q00592, 4145 30th St)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "San Diego", "location": "Vons (Q00615, 4725 Clairemont Dr)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "San Diego", "location": "Vons (Q00888, 3550 Murphy Canyon Rd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "San Diego", "location": "Vons (Q00889, 10675 Scripps Poway Pkwy)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "San Diego", "location": "Vons (Q01266, 7895 Highlands Village Pl)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "San Dimas", "location": "Albertsons (Q00496, 220 E Bonita Ave)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "San Francisco", "location": "Safeway (Q00920, 735 7th Ave)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "San Francisco", "location": "Safeway (Q01345, 5290 Diamond Heights Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "San Jose", "location": "Lucky (Q00921, 3457 McKee Rd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "San Jose", "location": "Safeway (Q00925, 5760 Cottle Rd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "San Jose", "location": "Safeway (Q00934, 1663 Branham Ln)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "San Jose", "location": "Safeway (Q00937, 4950 Almaden Expy)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "San Jose", "location": "Safeway (Q00986, 179 Branham Ln)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "San Jose", "location": "Safeway (Q00991, 1530 Hamilton Ave)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "San Jose", "location": "Safeway (Q01526, 5146 Stevens Creek Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "San Jose", "location": "Safeway (Q01529, 6150 Bollinger Rd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "San Jose", "location": "FoodMaxx (Q01752, 1539 Parkmoor Ave)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "San Leandro", "location": "Safeway (Q01160, 699 Lewelling Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "San Marcos", "location": "WinCo Foods (Q00479, 555 Grand Ave)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "San Marcos", "location": "Albertsons (Q00502, 151 Woodland Pkwy)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "San Marcos", "location": "Albertsons (Q00877, 1929 W San Marcos Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "San Marcos", "location": "Albertsons (Q01022, 1571 San Elijo Rd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "San Marcos", "location": "Ralphs (Q01717, 306 S Twin Oaks Valley Rd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "San Mateo", "location": "Safeway (Q01134, 100 De Anza Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "San Mateo", "location": "Safeway (Q01260, 1655 S El Camino Real)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "San Pedro", "location": "Albertsons (Q00177, 28090 S Western Ave)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "San Ramon", "location": "Safeway (Q01039, 11060 Bollinger Canyon Rd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Santa Ana", "location": "Food 4 Less (Q00320, 2140 S Bristol St)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Santa Ana", "location": "Vons (Q00414, 3650 S Bristol St)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Santa Clarita", "location": "Albertsons (Q00487, 27631 Bouquet Canyon Rd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Santa Clarita", "location": "Food 4 Less (Q01656, 19200 Soledad Canyon Rd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Santa Cruz", "location": "Safeway (Q01338, 2203 Mission St)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Santa Paula", "location": "Vons (Q00513, 576 W Main St)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Santa Rosa", "location": "Safeway (Q00623, 1799 Marlow Rd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Santa Rosa", "location": "Safeway (Q00632, 100 Calistoga Rd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Santa Rosa", "location": "Safeway (Q00672, 2300 Mendocino Ave)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Santa Rosa", "location": "Safeway (Q00976, 2751 4th St)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Santa Rosa", "location": "FoodMaxx (Q01256, 2055 Sebastopol Rd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Santa Rosa", "location": "Safeway (Q01339, 1211 W College Ave)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Santa Rosa", "location": "Safeway (Q01484, 2785 Yulupa Ave)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Santee", "location": "Vons (Q01655, 9643 Mission Gorge Rd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Saratoga", "location": "Safeway (Q01521, 12876 Saratoga Sunnyvale Rd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Saugus", "location": "Vons (Q01223, 26518 Bouquet Canyon Rd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Scotts Valley", "location": "Safeway (Q01331, 253 Mt Hermon Rd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Sebastopol", "location": "Safeway (Q01514, 406 N Main St)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Sherman Oaks", "location": "Pavilions (Q00469, 14845 Ventura Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Simi Valley", "location": "Albertsons (Q00465, 1268 Madera Rd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Simi Valley", "location": "Vons (Q00486, 1855 Cochran St)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Simi Valley", "location": "Vons (Q00504, 2938 Tapo Canyon Rd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Sonoma", "location": "Safeway (Q01536, 477 W Napa St)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "South San Francisco", "location": "Safeway (Q01351, 30 Chestnut Ave)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "South San Francisco", "location": "Safeway (Q01532, 2255 Gellert Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Spring Valley", "location": "Albertsons (Q01218, 543 Sweetwater Rd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Stevenson Ranch", "location": "Ralphs (Q01690, 24975 Pico Canyon Rd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Stockton", "location": "Safeway (Q00975, 6445 Pacific Ave)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Stockton", "location": "Safeway (Q01057, 2808 Country Club Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Sunnyvale", "location": "Safeway (Q00611, 639 S Bernardo Ave)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Sunnyvale", "location": "Safeway (Q01503, 150 E El Camino Real)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Temecula", "location": "WinCo Foods (Q01185, 40435 Winchester Rd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Thousand Oaks", "location": "Vons (Q00507, 2048 E Avenida de Los Arboles)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Thousand Oaks", "location": "Vons (Q01783, 1790 N Moorpark Rd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Torrance", "location": "Vons (Q00423, 4705 Torrance Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Torrance", "location": "Vons (Q00706, 24325 Crenshaw Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Tracy", "location": "Safeway (Q00972, 1801 W 11th St)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Tracy", "location": "WinCo Foods (Q01325, 2850 Pavilion Pkwy)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Tustin", "location": "Albertsons (Q00348, 13270 Newport Ave)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Union City", "location": "Safeway (Q00979, 1790 Decoto Rd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Upland", "location": "Albertsons (Q00661, 1910 N Campus Ave)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Upland", "location": "Vons (Q00731, 81 W Foothill Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Vacaville", "location": "Safeway (Q01346, 2090 Harbison Dr)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Valencia", "location": "Albertsons (Q00478, 23850 Copper Hill Dr)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Valencia", "location": "Vons (Q01216, 25850 The Old Rd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Vallejo", "location": "Safeway (Q01523, 122 Robles Way)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Van Nuys", "location": "Food 4 Less (Q00370, 16530 Sherman Way)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Ventura", "location": "Vons (Q01123, 115 W Main St)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Vista", "location": "Albertsons (Q00488, 1301 E Vista Way)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Vista", "location": "Albertsons (Q00516, 1601 S Melrose Dr)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Walnut Creek", "location": "Safeway (Q00936, 2800 Ygnacio Valley Rd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "West Covina", "location": "Food 4 Less (Q00248, 615 N Azusa Ave)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "West Hollywood", "location": "Pavilions (Q00415, 8969 Santa Monica Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Westminster", "location": "Albertsons (Q00662, 6755 Westminster Blvd.)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Whittier", "location": "Vons (Q00327, 15740 La Forge St)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Wilmington", "location": "Food 4 Less (Q00410, 336 W Anaheim St)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Windsor", "location": "Safeway (Q01524, 9080 Brooks Rd S)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Yorba Linda", "location": "Vons (Q01240, 20445 Yorba Linda Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "CA", "city": "Yucaipa", "location": "Vons (Q00503, 33644 Yucaipa Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"}
];