// --- Utah Locations ---
const utah = [
  {"state": "UT", "city": "Brigham City", "location": "Smith's (Q00812, 156 S Main St)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "UT", "city": "Draper", "location": "Smith's (Q00787, 212 E 12300 S)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "UT", "city": "Herriman", "location": "WinCo Foods (Q01457, 11969 Carlsbad Way)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "UT", "city": "Lehi", "location": "Smith's (Q00793, 1550 E 3500 N)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "UT", "city": "Logan", "location": "WinCo Foods (Q01715, 1341 Main St)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "UT", "city": "Midvale", "location": "WinCo Foods (Q01449, 7020 S 700 W)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "UT", "city": "Ogden", "location": "Smith's (Q00798, 4275 Harrison Blvd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "UT", "city": "Ogden", "location": "WinCo Foods (Q01708, 205 W 12th St)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "UT", "city": "Payson", "location": "Smith's (Q00783, 632 S 100 W)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "UT", "city": "Pleasant Grove", "location": "Smith's (Q00792, 210 E 700 S)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "UT", "city": "Salt Lake City", "location": "Smith's (Q00791, 4065 S Redwood Rd)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "UT", "city": "Salt Lake City", "location": "Smith's (Q00794, 876 E 800 S)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "UT", "city": "Sandy", "location": "Smith's (Q00781, 2039 E 9400 S)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "UT", "city": "South Salt Lake", "location": "WinCo Foods (Q01451, 2193 S Main St)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "UT", "city": "West Jordan", "location": "Smith's (Q00795, 4080 W 9000 S)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "UT", "city": "West Valley City", "location": "Smith's (Q00784, 4643 S 4000 W)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "UT", "city": "West Valley City", "location": "Smith's (Q00802, 5620 W 4100 S)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
  {"state": "UT", "city": "West Valley City", "location": "WinCo Foods (Q01466, 2572 S 5600 W)", "notes": "Pokémon TCG vending", "type": "Pokémon TCG"},
];